catalog_name: dev
schema_name: datalab_1ai
table_name_prefix: sarah_hotel_data

parameters:
  learning_rate: 0.01
  n_estimators: 1000
  max_depth: 6

drop_columns:
  - Booking_ID
categorical_columns:
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type
numerical_columns:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests
target_variable:
  - booking_status
